### ISSUE TITLE
Can't resolve all parameters for CaptchaService: (?, ?, ?)

### ISSUE THREAD

**Issue by Alavi1412** [captcha-com/angular-captcha#1] opened 2017-11-28 11:29 UTC
I have followed the steps in npm for setting up this package but after adding this code:
```
BotDetectCaptchaModule.forRoot({
      captchaEndpoint: '/botdetect-java-captcha-api-path-at-server-side/botdetectcaptcha'
    })
```
to my appModule, the app log the following error in console:
```
compiler.js:466 Uncaught Error: Can't resolve all parameters for CaptchaService: (?, ?, ?).
    at syntaxError (compiler.js:466)
    at CompileMetadataResolver._getDependenciesMetadata (compiler.js:15547)
    at CompileMetadataResolver._getTypeMetadata (compiler.js:15382)
    at CompileMetadataResolver._getInjectableMetadata (compiler.js:15362)
    at CompileMetadataResolver.getProviderMetadata (compiler.js:15722)
    at eval (compiler.js:15633)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getProvidersMetadata (compiler.js:15593)
    at eval (compiler.js:15595)
    at Array.forEach (<anonymous>)
```

I don't use systemJS so I skip the systemJS step in npm

**Comment by mplestin** [comment] 2017-12-26 10:29
The issue is fixed in the latest version of the module.
Run the following command to get the latest version:
`` 
npm i angular-captcha@latest
``
Thanks for your report. 
If you have any further questions, please feel free to contact us again through [contact form on captcha.com](https://captcha.com/contact.html).

**Closed by mplestin** 2017-12-26 10:29 UTC
